version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
      - image: mongo:3.4.5

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: yarn bootstrap

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn run style
      - run: yarn run type-check
      - run: yarn test
      - run: bash <(curl -s https://codecov.io/bash)
